repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/miki725/importanize
    rev: 0.8.0-alpha2
    hooks:
      - id: importanize
        language_version: python3
        stages: [commit]

